### ISSUE TITLE
how to solve bad page error

### ISSUE THREAD

**Issue by balasivagnanam** [praxigento/mage_ext_login_as#1]
I have installed this plugin and then I made the configuration, enabled and then I saw the button in customer page and also in the customer grid, but if I click it it goes to a routing

http://synergo.com.sg/sample/ergoshop/index.php/admin/prxgt_lgas_front/login/as/

Which comes as a bad page that doesn't exist.

How to fix this?

**Comment by flancer64** [comment]
Could you give me a Magento version you use?

**Comment by balasivagnanam** [comment]
Magento ver. 1.9.2.0

**Comment by flancer64** [comment]
I'll check this Mage version.

**Comment by flancer64** [comment]
I have checked dev-master version on 1.9.2.0 - it works. Could you give me access to the sample shop?

**Comment by balasivagnanam** [comment]
sure I will.. emailed you.. in your personal email..

On Fri, Aug 7, 2015 at 12:44 AM, Alex Gusev notifications@github.com
wrote:

> I have checked dev-master version on 1.9.2.0 - it works. Could you give me
> access to the sample shop?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/praxigento/mage_ext_login_as/issues/1#issuecomment-128435716
> .

## 

Thanks,
Bala

**Comment by flancer64** [comment]
Please email me to alex@flancer.lv

**Comment by flancer64** [comment]
This was frontend routing bug. Fixed. Please use version 1.2.0 or above. This module is available at default PHP Composer repository (https://packagist.org/packages/praxigento/mage_ext_login_as).

Bala, thanks for you support!

**Comment by balasivagnanam** [comment]
@flancer64 you are awesome :) thanks a lot for fixing this and helping in this :)

**Comment by balasivagnanam** [comment]
will you be publishing this to magento connect sooner?

**Comment by flancer64** [comment]
Yes, I have published ext just now. You sample app has new updated version of the module.

**Comment by LuizSantos1** [comment]
Please make it compatible with Magento 1.9.3.2 and 1.9.3.3 after Security patch 9767, it has stopped working

**Comment by flancer64** [comment]
Hello, @LuizSantos1 .

As I see, v. 1.9.3.3 has SUPEE-9767 included. I've just checked 2 stores under Magento 1.9.3.3 - LoginAs ext works correctly. Could you give some error messages (php_errors.log, apache_error.log or ./var/report/XXXXXXX) related to this issue?

**Comment by LuizSantos1** [comment]
There's no log error in php_errorlog

Is there any other file that I should see?


I am not getting any error, only a 404 page not found error

So it is probably a link route error... Which I have been investigating

and in foruns they say it is releated with security patches 9767 and 6788 and so on...


My site is: www.ultraeletronicos.com<http://www.ultraeletronicos.com> my theme is fortis

[https://lh3.googleusercontent.com/ZA9qu73TfbIeu68IIpuv39XgKJtIoODyZgDHZKywJa-Ae7sc3y85Djo5yoLkW2CnM3JoFsMZtKy65X5uIyN6uVZrYhVr2JcqC8-13wPE9eINeDHDeRClQSqPw7cImFW3pwoc6uEuI8YMg_Ywfsakaqb08ynti8rNDNyPjYuZCdx_5sOcMw7pZMhDvXdWRdmW4yZe5m4VuEejvaY-fCozZoJFB-b725FUGaPp6_-smtMy7fg09zhWsXa4hFtgEz4I24nUnQAfGr0WUTI50G_r-7g2--uM_IMAQQSCnaHDvFpfD29KkmSwF_ni1Q8gCY2QbsE_HrFAicX379fTV38MwyZ-3dmPVZM0SDZAGnpiNlJhMBEOMf8JiSBvCwscaYnupsue2NHlqMFF56JUIz_er3qepRMHpRgA7MjHGej3SM-3shMZnGZk8-U7wAQVJz1_w7g0CkG59JTH15p4YiUYJvw1PSohpw9eKCP_QRTyKn1fSDHcc_up2gdOi_O6sVhVHYGoeshbIiRmNLKe7IXaaxlLkdblCqvZYjKb2b-mbtQrUzZTUUWT3mWK5Gk7XyoCok9VNgaljp7QhVDhjcXQtOJ6E9fhNNyqNhsmU_BfMLdBK5dY5zay=w960-h420-no]<http://www.ultraeletronicos.com/>

Ultra Eletrônicos<http://www.ultraeletronicos.com/>
www.ultraeletronicos.com
A Ultra Eletrônicos é uma site especializado na comercialização de eletrônicos, artigos esportivos e grandes marcas como: Apple, Samsung, Motorola, Android, iOS ...



________________________________
De: Alex Gusev <notifications@github.com>
Enviado: sexta-feira, 23 de junho de 2017 05:28:08
Para: praxigento/mage_ext_login_as
Cc: LuizSantos1; Mention
Assunto: Re: [praxigento/mage_ext_login_as] how to solve bad page error (#1)


Hello, @LuizSantos1<https://github.com/luizsantos1> .

As I see, v. 1.9.3.3 has SUPEE-9767 included. I've just checked 2 stores under Magento 1.9.3.3 - LoginAs ext works correctly. Could you give some error messages (php_errors.log, apache_error.log or ./var/report/XXXXXXX) related to this issue?

**Comment by LuizSantos1** [comment]
Hi there,

I have found the issue, but to solve it, security risks increases...

So I hope you manage to get an update release to solve this issue...


To avoid this admin route link issue you have to go to:

System - Configuration - Advanced - Admin and ENABLE

Admin routing compatibility mode for extensions


But doing it, leaves the whole site compromised as it can be suffer automoted attacks

using extensions vulnerabilities...

________________________________
De: Alex Gusev <notifications@github.com>
Enviado: sexta-feira, 23 de junho de 2017 05:28:08
Para: praxigento/mage_ext_login_as
Cc: LuizSantos1; Mention
Assunto: Re: [praxigento/mage_ext_login_as] how to solve bad page error (#1)


Hello, @LuizSantos1<https://github.com/luizsantos1> .

As I see, v. 1.9.3.3 has SUPEE-9767 included. I've just checked 2 stores under Magento 1.9.3.3 - LoginAs ext works correctly. Could you give some error messages (php_errors.log, apache_error.log or ./var/report/XXXXXXX) related to this issue?

**Comment by flancer64** [comment]
@LuizSantos1 , thanks for your investigation. I have changed "Admin routing compatibility mode for extensions" option to "Disabled" in "System - Configuration - Advanced - Security" section and have got the same error (404 - Page not found").

I'll try to fix it.

**Comment by flancer64** [comment]
@LuizSantos1 , fixed. You can try to use version 1.2.2 that works with disabled "Admin routing compatibility mode for extensions" option.

Thanks for your cooperation.

**Comment by LuizSantos1** [comment]
Thanks a lot, I will test it later.
Could you please tell us the files or lines changed? I am asking it because 
other extensions have the same issue, so I need to enable "Admin routing compatibility mode for extensions" all the time in order to use them, which is very time consuming... 

Thanks in advance!

**Comment by flancer64** [comment]
The main reason is a router's name in admin area. Compare [old version](https://github.com/praxigento/mage_ext_login_as/blob/269515d5c76dfcaf2d0d372829d11dd4e47618f2/src/app/code/community/Praxigento/LoginAs/etc/config.xml#L31) and [new one](https://github.com/praxigento/mage_ext_login_as/blob/master/src/app/code/community/Praxigento/LoginAs/etc/config.xml#L31).

Hope, it helps.
